### ISSUE TITLE
Updater download doesn't check for free storage space so could fill up the storage

### ISSUE THREAD

**Issue by tomvanbraeckel** [ducalex/retro-go#138] opened 2024-07-19 11:43 UTC
On the Fri3D Camp 2024 Badge, I disabled the download of updates in the menu because, if I read correctly, it doesn't do a free storage space check, so it could fill up the storage, especially if using the internal flash.

Note that, on the Fri3D Camp 2024 Badge, there's also no factory app to boot to (only MicroPython on OTA0 and OTA1) so I'm thinking about solutions for that. Perhaps I need to move odroid-go-multi-firmware's functionality to the launcher or components/retro-go/...?

**Comment by ducalex** [comment] 2024-07-19 17:05
I share your desire for a simpler updating system. However the updater can't be part of the launcher because it would have to overwrite itself and that's no good. It would be possible to bundle a small utility with retro-go that is able to reflash all the partitions except itself but it wouldn't be able to handle partition layout changes between versions (admittedly rare nowadays, so maybe an acceptable limitation?).

But the most robust self-updater would likely be your own version of the multi-firmware (modified to preserve/protect your shared vfs, and get rid of the multi if you don't want that).

**Comment by ducalex** [comment] 2024-07-19 17:08
I've just updated the code so that it deletes failed downloads to avoid unnecessary problems. Which should fix the issue in the title but not your overall updater problem.

**Comment by ducalex** [comment] 2024-07-19 19:00
I've implemented a self-updater. It works and instructions can be found in the commit: 

https://github.com/ducalex/retro-go/commit/6ec06678b61dd7084f09fbe11400adfedff2e333

To skip the download part you can place .fw files manually in the folder where it expects to find them and force reboot to the updater as described in the commit, a prompt will let you choose a file to flash.

Of course if I decide to merge this, the UX will need to be improved :)

**Comment by ducalex** [comment] 2024-07-21 16:27
> If that's not the case, why not? Is it because the app isn't fully loaded into RAM but rather memory mapped, and gets loaded "on demand" from internal flash? And as soon as you overwrite that part of the internal flash that's mapped to the app itself, it considers it "dirty" and reads it again?

Apps are indeed memory mapped. But since the flash is connected via SPI, parts of the app is copied to IRAM before being executed and you might be lucky to avoid a crash whilst overwriting the flash. I think enabling SPIRAM_FETCH_INSTRUCTIONS might make it okay to overwrite itself, I wasn't aware of that config option!

> I tested it with an in-place update using a big (8MB) .img file that includes a FAT partition with some demo games, worked great as well. It's very simple really, just overwrite the whole flash starting at 0x00 with a new image.

I think that's a reasonable approach for your project but that is not suitable for upstream retro-go, because the only thing we know for sure is that we own our partitions. We can't assume everything outside that to be free real estate.

**Comment by ducalex** [comment] 2024-07-21 19:06
What would be the advantage over using `esp_partition_write` for each partition?

**Comment by ducalex** [comment] 2024-07-21 21:30
> Doing raw flash writes but starting at a specific partition would allow updating multiple partitions in one go, 

Doing so would break if the partition layout changed slightly between updates (partition offsets, sizes, or order).

> without the user having to do each one separately.

But the demo I made will update all partitions present in the .fw, the user has nothing more to do?

**Comment by ducalex** [comment] 2024-07-21 22:39
As planned I've added .img support (untested) https://github.com/ducalex/retro-go/blob/self-updater/updater/main/main.c

Hopefully this clears up some misunderstandings about what my updater does?

**Comment by ducalex** [comment] 2024-07-26 15:59
I think for your project rewriting the entire flash including the partition table is fine, but this isn't something I want to pursue in retro-go because it breaks things like the odroid-go-multi-firmware which is used on at least half of our main targets. If I ever merge the updater into the project, it will only be able to update itself.

So I'm okay merging changes that make maintaining the patch on your side easier, but I won't be accepting a PR for the entire feature.

> Issue (2) can probably be fixed by checking whether there's enough free space in /sd or not. If yes, then it writes there, which is safer because then it can make sure the complete file is there (size/checksum) before proceeding. If not, then it shows an additional "warning, not enough free space to download first, are you sure you want to write directly to internal flash? don't interrupt it!" and if confirmed, does that.

I looked into what checking for free space entails when you first opened this issue but it seems we'd have to call fatfs's API directly which isn't ideal because it won't work with other file systems.

> http://elm-chan.org/fsw/ff/doc/getfree.html

I also didn't find a nice way to resolve the vfs path to the matching fatfs path. That being said I just merged the `rg_storage_get_free_space` I had stashed, maybe it will be good enough for your usage :) .

**Comment by ducalex** [comment] 2024-07-28 19:29
I'm not quite sure what I want to add to retro-go in regards to the self-updater. I will have to do some testing to make sure the launcher updating itself in place doesn't cause issues (I know you've tested, but this seems like something I need to see for myself and need to be careful about.)

> One more change I have is that I only show .img files in the updater. Wouldn't this (if we also add .fw files) make sense for upstream retro-go? The reason for this is that a release might contain a few other files, and to avoid the user selecting those for the update. 

You're right! I improved `rg_extension_match` and now filter the list of assets with it, showing .fw and .img only.

**Comment by ducalex** [comment] 2024-08-01 16:15
> Could it be that the partition table is different between your old and updated version? Maybe that has something to do with it...

The partition table is the same in my test and isn't overwritten.

> Does it crash during the write to flash?

Usually yes but sometimes it crashes during erasing too, depending how big I make my blocks.

> Could you elaborate on "not working well"? Is it crashing? If yes, do you have a stacktrace? Or is it hanging, glitching,...?

The crash differs depending on the new flash layout, it might jump to a valid place or not. Usually it does weird things and ends up panicking. A stack trace would be meaningless since I'm flashing a binary that has a different layout over the old binary. But sure I'll join a log at the end.


Here's a log of me flashing a new launcher over the existing launcher. The new launcher works when flashed over serial or via odroid-go-multi-firmware. In this test I was erasing/writing blocks of only 4KB to increase odds of success. I was only writing to the launcher partition. The new image differs in the following ways: I changed optimization flags, disabled networking, disabled nano lib, changed some buffer sizes in esp-idf. Just things to force the layout to be different.


[log.txt](https://github.com/user-attachments/files/16459256/log.txt)

**Comment by ducalex** [comment] 2024-08-05 18:16
I had both in my `sdkconfig` and confirmed that the esp-idf version I was using supported them. But after looking more into it they seem to only do something on the S2/S3!

That must be why I can't get it not to crash and you can. Mine on ESP32 is still running from Flash, yours isn't hence no crash.

So I guess that feature could only apply to the S3 targets (and with enough PSRAM)? :(

**Comment by ducalex** [comment] 2024-08-22 19:27
Okay I agree, the original issue is fixed so this can be closed. Feel free to open another issue to discuss in-place updates :) but as I said it would have to support esp32 somehow...

**Closed by ducalex** 2024-08-22 19:27 UTC
Labels: bug
