### ISSUE TITLE
Launcher: LCD backlight flickering

### ISSUE THREAD

**Issue by mtojek** [ducalex/retro-go#50] opened 2022-11-01 12:10 UTC
Hi,

The LCD screen seems to be flickering if I set the backlight level < 100%. I can observe it only in the launcher and it looks like the screen is being continuously redrawed.

**Comment by KD-MM2** [comment] 2022-11-01 13:08
I don't think is a software related problem.
Are you using the Odroid-Go or custom diy? If it's custom diy, is lcd module or lcd only? If module, the voltage to module's VCC pin?

**Comment by mtojek** [comment] 2022-11-01 13:14
> I don't think is a software related problem.

I can't observe it while playing games. I can see it only in the launcher selection screen. It also stops flickering when I press the MENU/OPTIONS button.

> Are you using the Odroid-Go or custom diy? If it's custom diy, is lcd module or lcd only? If module, the voltage to module's VCC pin?

Custom DIY with LCD module. The module has 3v3 regulator, so it requires 5v on VCC the pin.

**Comment by KD-MM2** [comment] 2022-11-01 13:39
I got the same issue before too, this trick works for me. Skip the regulator by jumping J1 on the lcd module, then 3v3 to the vcc pin.

**Comment by mtojek** [comment] 2022-11-01 14:50
Thanks! Jumping J1 fixes the issue, but then I can hear a crackle from speaker when I enable the circuit. This is ESP32 DevkitC v4 and I'm using its internal AMS regulator to expose 3v3.

**Comment by KD-MM2** [comment] 2022-11-01 16:34
i2s dac or internal dac with amp? which amp board?

**Comment by KD-MM2** [comment] 2022-11-01 16:57
My diy custom. Working good except some super small noise while charging.
Parts list: lilygo t7 v1.5(esp32-wrover-e 16mb eeprom/8mb psram, support battery), ili9341 2.8 lcd, pam8302 2.5w amp(with some small changes on the module to use fixed volume input), 7mm buttons(default odroid-go schematic).

![DBF9CABD-E7C7-429D-AC60-058CB30FA58E](https://user-images.githubusercontent.com/57068549/199291305-68b62033-378e-4db8-bc12-5b7077830bfe.jpeg)

![2BD7FB24-4C1F-49FA-AC1E-237FCA9445FA](https://user-images.githubusercontent.com/57068549/199289418-729a1cc4-2c6e-432a-b3a2-5f504484cd96.jpeg)

**Comment by mikeinkl1** [comment] 2022-11-02 01:24
> > I don't think is a software related problem.
> 
> I can't observe it while playing games. I can see it only in the launcher selection screen. It also stops flickering when I press the MENU/OPTIONS button.
> 
> > Are you using the Odroid-Go or custom diy? If it's custom diy, is lcd module or lcd only? If module, the voltage to module's VCC pin?
> 
> Custom DIY with LCD module. The module has 3v3 regulator, so it requires 5v on VCC the pin.

Got the exact same issue with my selfbuilt retroesp32 boards. With only the lanuncher open the speaker crackles and the backlight flickers. With the menu open it stops. I thought the issue is sd card activity.  The pcb routing isnt great and there is crosstalk between the sd lines and the audio line. The crackling causes the amp to draw more power and that draws down the backlight voltage. Some boards are worse than others so it looks the underlying issue is the hardware design but it can be improved or fixed in software.

**Comment by 32teeth** [comment] 2022-11-02 12:58
> Got the exact same issue with my selfbuilt retroesp32 boards

Are you referring to my boards? [Retro ESP32 Hardware](https://github.com/retro-esp32/RetroESP32-Hardware)

I recently released (8 months ago) a slimmed version without the FTDI chip, reducing noise, cost, added usb c +  programming header.

I can confirm that you will get flicker if the programming header is plugged in and the device power switch is set to OFF. Thats just a power supply issue. Move the power switch to ON position and signal noise is gone.

Once you are done programming, power from LiPo or USB, flicker doesn't happen

**Comment by mikeinkl1** [comment] 2022-11-02 14:58
Yes got some of of your pcbs made. [Pic](https://user-images.githubusercontent.com/85822619/189537381-64d09af3-9ca7-49e2-bf08-caa4ba670867.jpg) 

Agree ii is a power issue. I used a larger c7 because the audio was too low. 220pf is far lower than what the datasheet suggests. Then the audio was ok when using the emulators but it made the screenflicker and audio noise worse. I think the launcher must be constantly polling the sd card whereas the games dont. Audio and sd traces run parallel which also doesnt help. 
Was planning on re designing the board when i find time. Maybe with a s32s3 and i2s audio. That should avoid some of the issues.

**Comment by mikeinkl1** [comment] 2022-11-04 09:23
software solution is in 
g_input_read_battery: noise to signal ratio #51

**Comment by ducalex** [comment] 2022-11-04 21:00
Can anyone attach a short video of the flicker, for reference?

**Comment by mikeinkl1** [comment] 2022-11-05 06:27
https://user-images.githubusercontent.com/85822619/200106134-034ee9bf-5684-4e6c-b592-9be337a34293.mp4

**Comment by ducalex** [comment] 2024-05-03 14:11
I'm doing some spring cleaning of issues inactive for 1-2 years.

Is this issue still relevant? And if has anyone made progress in improving the situation?

**Comment by ducalex** [comment] 2024-08-22 19:29
No feedback so I'll assume the original issue is resolved. Feel free to open a new issue to discuss any remaining issue :)

**Closed by ducalex** 2024-08-22 19:29 UTC
