### ISSUE TITLE
Build Error on PRBOOM

### ISSUE THREAD

**Issue by 32teeth** [ducalex/retro-go#54] opened 2022-11-02 00:02 UTC
**Describe the bug**

* did a rebase
*  **run** `python3 rg_tool.py --target retro-esp32 build-img`
*  **error** `components/retro-go/config.h:32:25: error: expected declaration specifiers or '...' before string constant
 #define RG_APP_LAUNCHER "launcher"` 
* **error** `prboom-go/components/prboom/doomdef.h:47:72: error: expected declaration specifiers or '...' before numeric constant #define exit(x) rg_system_switch_app(RG_APP_LAUNCHER, RG_APP_LAUNCHER, 0, 0);`

Also tried full clean

**Comment by 32teeth** [comment] 2022-11-02 00:06
Or...  ...where can i comment out prboom in `build-img all`

**Comment by 32teeth** [comment] 2022-11-02 12:52
Thanks @mikeinkl1 
I simply just commented it out since i did not want it in my build ;)

**Comment by ducalex** [comment] 2022-11-03 18:45
Duplicate of #45

**Closed by ducalex** 2022-11-03 18:45 UTC
